name: Publish to PyPI

on:
  workflow_dispatch: 

permissions:
  contents: read
  deployments: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/project/pythonmetatrader5/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tools
        run: python -m pip install --upgrade build twine

      - name: Clean previous builds
        run: rm -rf dist build *.egg-info

      - name: Build package
        run: python -m build

      - name: Twine check
        run: twine check dist/*

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload --skip-existing dist/*
